<?php

namespace App\Http\Middleware;

use Carbon\Carbon;
use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\Response;

/**
 * Resolves the request's locale, in priority order:
 *   1. The authenticated user's saved preference (users.language)
 *   2. The 'locale' cookie
 *   3. The browser's Accept-Language header
 *   4. 'en'
 *
 * Registered globally (app/Http/Kernel.php $middleware) so it runs on every
 * request — public pages, auth pages, and the admin panel alike — before
 * any view renders. It only ever reads the locale from server-side signals
 * (session/DB/cookie/header); nothing in the URL or request body picks it,
 * so switching languages never changes routes.
 */
class SetLocale
{
    public const SUPPORTED = ['en', 'fr', 'ar'];

    public function handle(Request $request, Closure $next): Response
    {
        $cookieLocale = $request->cookie('locale');
        $locale = $this->resolve($request, $cookieLocale);

        App::setLocale($locale);
        // diffForHumans()/format() dates (e.g. "Updated 3 days ago" on
        // Course Details) are generated by Carbon, not Laravel's own
        // translator, so it needs its locale set separately.
        Carbon::setLocale($locale);

        /** @var Response $response */
        $response = $next($request);

        // Keep guests consistent across requests without needing a DB row.
        // A logged-in user's own preference always wins on the next
        // request regardless of what's in this cookie, so it's safe to
        // just mirror whatever locale was actually resolved/used here.
        if ($cookieLocale !== $locale) {
            $response->headers->setCookie(cookie('locale', $locale, 60 * 24 * 365));
        }

        return $response;
    }

    private function resolve(Request $request, ?string $cookieLocale): string
    {
        $user = Auth::user();
        if ($user && $user->language && in_array($user->language, self::SUPPORTED, true)) {
            return $user->language;
        }

        if ($cookieLocale && in_array($cookieLocale, self::SUPPORTED, true)) {
            return $cookieLocale;
        }

        $preferred = $request->getPreferredLanguage(self::SUPPORTED);

        return $preferred ?? 'en';
    }
}
